# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
project_name: space
builds:
  # Builds everything except macos
  - id: space
    env:
      - CGO_ENABLED=0
    main: ./cmd/space-poc/main.go
    binary: space
    goos:
      - linux

  # Using separate builds for each macos chipset since each uses a different gon config

  # Builds macos for amd64 chips
  - id: space-darwin-amd64
    goarch:
        - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/space-poc/main.go
    binary: space
    goos:
      - darwin
    # hooks:
    #   post: gon -log-level debug ci/gon-amd64.hcl
  # Builds macos for i386 chips
  - id: space-darwin-386
    goarch:
        - "386"
    env:
      - CGO_ENABLED=0
    main: ./cmd/space-poc/main.go
    binary: space
    goos:
      - darwin
    # hooks:
      # post: gon -log-level debug -log-json ci/gon-386.hcl
archives:
- name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
  format: binary
  files:
    - LICENSE*
    - README*
    - CHANGELOG*
    - dist/space-macos-i386.dmg
    - dist/space-macos-x86_64.dmg
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
