version: '3.7'

services:
  ipfs:
    image: ipfs/go-ipfs:v0.6.0
    environment:
      - IPFS_PROFILE=local-discovery
    ports:
      - 5001:5001

  mongo:
    image: mongo:latest
    ports:
      - 27027:27017


