name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: macos-latest
    name: goreleaser
    steps:
      - uses: actions/checkout@v2
      - name: Unshallow Fetch
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14.0'
      - name: Add MacOS certs
        run: cp ./ci/add-osx-cert.sh /tmp/add-osx-cert.sh && chmod +x /tmp/add-osx-cert.sh && /tmp/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}